'use client'

import { useMemo, useState } from 'react'
import { ArrowRight, BatteryCharging, Check, ChevronDown, ChevronRight, MapPin, Menu, Search, ShieldCheck, Sparkles, X, Zap } from 'lucide-react'

const cars = [
  {id:'discover',name:'e-Discover',price:'₹7.99 L',monthly:[25800,23100,21500,19900,17800,16100],battery:'30 kWh',range:'275 km',tag:'Your first electric experience'},
  {id:'explore',name:'e-Explore',price:'₹14.99 L',monthly:[45300,40600,37700,34900,31100,28300],battery:'49 kWh',range:'440 km',tag:'Go further, with confidence'},
  {id:'prestige',name:'e-Prestige',price:'₹19.99 L',monthly:[63500,56900,52900,48900,43600,39600],battery:'61 kWh',range:'543 km',tag:'All-in on electric'},
]
const tenures=[3,6,9,12,24,36]
const faqs=[['What is Suzuki Drive?','Suzuki Drive is an EV-only leasing and subscription experience designed to let you experience electric mobility before committing to ownership.'],['How long can I lease an EV?','Choose a tenure from 3 to 36 months. Monthly pricing changes with the selected tenure.'],['What is included?','Insurance, road tax, roadside assistance, scheduled service, tyres, doorstep delivery and pickup, a battery-health certificate and a buy-out option are included across the range.'],['Can I buy my leased EV?','Yes. At the end of your subscription, you can choose to return your EV or buy the exact leased car at its applicable residual value.'],['Where can I charge?','Suzuki Drive connects you to a broad public charging ecosystem, with charging support varying by vehicle tier.'],['Is corporate leasing available?','Yes. Suzuki Drive has a dedicated corporate leasing proposition for organisations and employee mobility programmes.']]

export default function SuzukiDrive(){
  const [mobileOpen,setMobileOpen]=useState(false)
  const [slide,setSlide]=useState(0)
  const [persona,setPersona]=useState('discover')
  const [filter,setFilter]=useState('all')
  const [tenure,setTenure]=useState(12)
  const [faq,setFaq]=useState<number|null>(null)
  const [state,setState]=useState('')
  const [city,setCity]=useState('')
  const [toast,setToast]=useState('')
  const car=cars[slide]
  const filtered=useMemo(()=>filter==='all'?cars:cars.filter(c=>c.id===filter),[filter])
  const notify=(m:string)=>{setToast(m);setTimeout(()=>setToast(''),2500)}
  const go=(id:string)=>{document.getElementById(id)?.scrollIntoView({behavior:'smooth'});setMobileOpen(false)}

  return <main>
    {toast&&<div className="toast"><Check size={16}/>{toast}</div>}
    <header className="header"><div className="brand" onClick={()=>go('home')}><span className="smark">S</span><span>SUZUKI <b>DRIVE</b></span></div><nav className="nav"><button onClick={()=>go('leasing')}>Leasing</button><button onClick={()=>go('range')}>Explore EVs</button><button onClick={()=>go('sustainability')}>Sustainability</button><button onClick={()=>go('about')}>About</button><button onClick={()=>go('faqs')}>FAQs</button></nav><div className="actions"><button className="link" onClick={()=>go('dashboard')}>Login</button><button className="primary small" onClick={()=>go('range')}>Find Your EV <ArrowRight size={16}/></button></div><button className="hamb" onClick={()=>setMobileOpen(!mobileOpen)}>{mobileOpen?<X/>:<Menu/>}</button></header>
    {mobileOpen&&<div className="mobileNav"><button onClick={()=>go('leasing')}>Leasing</button><button onClick={()=>go('range')}>Explore EVs</button><button onClick={()=>go('sustainability')}>Sustainability</button><button onClick={()=>go('about')}>About</button><button onClick={()=>go('faqs')}>FAQs</button><button onClick={()=>go('dashboard')}>Login</button></div>}

    <section id="home" className="hero"><div className="heroCopy"><div className="eyebrow"><Zap size={14}/> ELECTRIC, THE SUZUKI WAY</div><h1>Rent the confidence.<br/><em>Then sell the car.</em></h1><p>Experience an EV on your terms. From 3 to 36 months, Suzuki Drive makes going electric simpler, more flexible and more familiar.</p><div className="heroButtons"><button className="primary" onClick={()=>go('range')}>Find Your EV <ArrowRight size={18}/></button><button className="secondary" onClick={()=>go('leasing')}>How Suzuki Drive works</button></div><span className="terms">*Terms and Conditions apply.</span></div><div className="heroVisual"><div className={'carArt '+car.id}><div className="carGlow"/><div className="carShape"><div className="roof"/><div className="window"/><div className="wheel w1"/><div className="wheel w2"/></div><div className="modelBadge"><span>{car.tag}</span><strong>{car.name}</strong></div></div><div className="carousel"><button onClick={()=>setSlide((slide+2)%3)}>←</button><div>{cars.map((c,i)=><button key={c.id} className={i===slide?'active':''} onClick={()=>setSlide(i)}>{String(i+1).padStart(2,'0')}</button>)}</div><button onClick={()=>setSlide((slide+1)%3)}>→</button></div></div></section>

    <section className="reviews"><div><strong>Designed for real life.</strong><span>Backed by Suzuki confidence.</span></div><div className="review">★★★★★ <b>“The easiest way to finally try an EV.”</b><small>— Suzuki Drive customer</small></div><div className="review">★★★★★ <b>“Flexible enough for how I actually drive.”</b><small>— Suzuki Drive customer</small></div></section>

    <section id="range" className="section"><div className="sectionHead"><div><span className="eyebrow">FIND YOUR EV</span><h2>There’s an electric<br/>experience for you.</h2></div><p>Not sure where to start? Tell us how you think about EVs. We’ll point you in the right direction.</p></div><div className="personas">{[['discover','I’m New to EVs','Dip your toes in. Meet the e-Discover.'],['explore','I’ve Experienced an EV','Want more? Step into the e-Explore.'],['prestige','I’m All-in on Electric','No compromises. Meet the e-Prestige.']].map(([id,title,desc])=><button key={id} className={'persona '+(persona===id?'selected':'')} onClick={()=>{setPersona(id);setFilter(id)}}><span className="radio">{persona===id&&<i/>}</span><div><b>{title}</b><span>{desc}</span></div><ChevronRight/></button>)}</div><div className="filterRow"><span>Explore the range</span><div>{[['all','All EVs'],['discover','e-Discover'],['explore','e-Explore'],['prestige','e-Prestige']].map(([v,l])=><button className={filter===v?'on':''} key={v} onClick={()=>setFilter(v)}>{l}</button>)}</div></div><div className="cars">{filtered.map(c=><article className="carCard" key={c.id}><div className={'miniCar '+c.id}><div className="miniShape"><div className="miniWindow"/><div className="miniWheel a"/><div className="miniWheel b"/></div></div><div className="carInfo"><span>{c.tag}</span><h3>{c.name}</h3><div className="specs"><span><b>{c.range}</b> range</span><span><b>{c.battery}</b> battery</span></div><div className="price"><span>from</span><b>₹{c.monthly[3].toLocaleString('en-IN')}<small>/month</small></b></div><button className="outline" onClick={()=>{setSlide(cars.findIndex(x=>x.id===c.id));go('leasing')}}>Lease {c.name} <ArrowRight size={16}/></button></div></article>)}</div></section>

    <section id="leasing" className="darkSection"><div className="sectionHead light"><div><span className="eyebrow">HOW SUZUKI DRIVE WORKS</span><h2>Try electric.<br/>Without the leap.</h2></div><p>One simple journey from choosing your EV to driving it, with the flexibility to decide what comes next.</p></div><div className="steps">{[['01','Choose your EV','Pick the car that fits your life.'],['02','Choose your tenure','3–36 months, with monthly pricing that changes with your plan.'],['03','Drive with confidence','Insurance, service and roadside support are built into the experience.'],['04','Return or buy','At the end, return your EV or buy your exact leased car at applicable residual value.']].map(s=><div className="step" key={s[0]}><span>{s[0]}</span><h3>{s[1]}</h3><p>{s[2]}</p></div>)}</div><div className="leasePlanner"><div><span className="eyebrow">LIVE PRICE EXAMPLE</span><h3>{car.name}</h3><p>Choose your tenure</p><div className="tenures">{tenures.map(t=><button key={t} className={tenure===t?'chosen':''} onClick={()=>setTenure(t)}>{t}m</button>)}</div></div><div className="monthly"><span>Estimated monthly subscription</span><strong>₹{car.monthly[tenures.indexOf(tenure)].toLocaleString('en-IN')}</strong><small>for {tenure} months · *Terms and Conditions apply.</small><button className="primary" onClick={()=>notify('Application started — this demo flow is ready for integration.')}>Start your application <ArrowRight/></button></div></div></section>

    <section className="section included"><div className="sectionHead"><div><span className="eyebrow">WHAT’S INCLUDED</span><h2>More than a car.<br/>A complete experience.</h2></div><p>Every Suzuki Drive plan is designed around the things that make EV ownership feel effortless.</p></div><div className="benefits">{[['Insurance & road tax','Covered across the range.'],['Roadside assistance','Support when you need it.'],['Scheduled service & tyres','Maintenance built in.'],['Doorstep delivery & pickup','We bring the experience to you.'],['Battery-health certificate','Know the health of your battery.'],['Tier swap','One swap per tenure, across tiers.'],['Buy-out option','Buy your exact leased EV at applicable residual value.'],['Charging support','Access varies by vehicle tier.']].map(([a,b])=><div className="benefit" key={a}><div className="icon"><ShieldCheck size={20}/></div><b>{a}</b><span>{b}</span></div>)}</div></section>

    <section className="charging"><div className="chargeVisual"><div className="chargeOrb"><BatteryCharging size={70}/></div><div className="chargeLine"/></div><div><span className="eyebrow">CHARGING</span><h2>Charge with<br/><em>confidence.</em></h2><p>Suzuki Drive connects your EV journey to a wide charging ecosystem, with charging support built into the higher tiers.</p><div className="chargeStats"><div><strong>2,000+</strong><span>charge points</span></div><div><strong>1,100+</strong><span>cities</span></div><div><strong>13</strong><span>CPO partners</span></div></div><button className="secondary" onClick={()=>notify('Charger finder coming next.')}>Find a charger <ArrowRight size={17}/></button></div></section>

    <section id="sustainability" className="section sustainability"><div className="sectionHead"><div><span className="eyebrow">SUSTAINABILITY</span><h2>Electric is only<br/>the beginning.</h2></div><p>Suzuki Drive is designed as a full battery lifecycle system — using real-world intelligence to improve vehicles, residual value and circularity.</p></div><div className="sustainGrid">{[['01','REAL-WORLD DATA','Telemetry turns every kilometre into an engineering signal.'],['02','BATTERY HEALTH','Track state of health and provide a battery-health certificate.'],['03','SECOND LIFE','Create a pathway from fleet use to energy storage.'],['04','MATERIAL RECOVERY','Move toward a closed-loop battery lifecycle.']].map(([n,t,d])=><div key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div><div className="impact"><div><strong>611M</strong><span>km fleet distance modelled, FY27–31</span></div><div><strong>26,394</strong><span>tonnes CO₂ avoided, modelled</span></div><div><strong>168 MWh</strong><span>second-life battery capacity</span></div></div></section>

    <section id="about" className="about"><div><span className="eyebrow">WHY SUZUKI DRIVE</span><h2>Confidence is<br/>the missing piece.</h2><p>Suzuki Drive brings Suzuki’s automotive scale, EV-focused R&D, service network and charging ecosystem into one customer journey.</p><button className="primary" onClick={()=>go('range')}>Explore the EV range <ArrowRight/></button></div><div className="aboutCard"><Sparkles size={26}/><h3>Trial → Trust → Conversion</h3><p>Experience real-world range, charging behaviour, running costs and battery health — then make your own decision.</p><div className="progress"><i/><i/><i/><i/><i/></div><span>THE SUZUKI DRIVE FLYWHEEL</span></div></section>

    <section className="dealer"><div className="dealerCopy"><span className="eyebrow">FIND A DEALER</span><h2>Your EV journey<br/>starts nearby.</h2><p>Find a Suzuki location that can help you explore the Drive experience.</p></div><div className="dealerBox"><label>State<select value={state} onChange={e=>setState(e.target.value)}><option value="">Select state</option><option>Maharashtra</option><option>Karnataka</option><option>Telangana</option><option>Delhi</option></select></label><label>City<select value={city} onChange={e=>setCity(e.target.value)}><option value="">Select city</option><option>Mumbai</option><option>Pune</option><option>Bengaluru</option><option>Hyderabad</option><option>New Delhi</option></select></label><div className="dealerBtns"><button className="secondary" onClick={()=>notify(state&&city?`Searching Suzuki locations in ${city}.`:'Select a state and city first.')}>Search <Search size={16}/></button><button className="outline" onClick={()=>notify('Location access would be requested here.')}>Use My Location <MapPin size={16}/></button></div></div></section>

    <section id="faqs" className="section faqSection"><div className="sectionHead"><div><span className="eyebrow">FAQs</span><h2>Questions,<br/>answered.</h2></div><p>Everything you need to know before you start your electric journey.</p></div><div className="faqs">{faqs.map(([q,a],i)=><div className={'faq '+(faq===i?'open':'')} key={q}><button onClick={()=>setFaq(faq===i?null:i)}><span>{q}</span><ChevronDown/></button>{faq===i&&<p>{a}</p>}</div>)}</div></section>

    <section id="dashboard" className="dashboard"><div className="dashTop"><div><span className="eyebrow">CUSTOMER DASHBOARD</span><h2>Your Drive,<br/>all in one place.</h2></div><button className="secondary" onClick={()=>notify('Demo dashboard is ready for integration.')}>Open dashboard <ArrowRight/></button></div><div className="dashGrid">{['Dashboard','Profile','My Applications','My Subscription','Payments','Documents','Vehicle','Service & Maintenance','Charging','End of Subscription'].map((x,i)=><button key={x} onClick={()=>notify(i===9?'Return or buy your exact leased EV.':`${x} selected.`)}><span>0{i+1}</span><b>{x}</b><ChevronRight/></button>)}</div><div className="endCards"><div><span>END OF SUBSCRIPTION</span><h3>Return your EV</h3><p>Hand your EV back through the Suzuki Drive return journey.</p><button onClick={()=>notify('Return flow selected.')}>Start return <ArrowRight/></button></div><div><span>END OF SUBSCRIPTION</span><h3>Buy your EV</h3><p>Buy the exact car you leased at its applicable residual value.</p><button onClick={()=>notify('Buy flow selected.')}>Explore buy-out <ArrowRight/></button></div></div></section>

    <footer><div className="brand"><span className="smark">S</span><span>SUZUKI <b>DRIVE</b></span></div><p>Rent the confidence. Then sell the car.</p><div><button onClick={()=>go('about')}>About</button><button onClick={()=>go('faqs')}>FAQs</button><button onClick={()=>go('sustainability')}>Sustainability</button></div><small>© Suzuki Drive · Concept experience · *Terms and Conditions apply.</small></footer>
    <button className="stickyCta" onClick={()=>go('range')}>Find Your EV <ArrowRight size={17}/></button>
  </main>
}