import Link from 'next/link'
import SiteHeader from '../../components/SiteHeader'

export default function Corporate(){return <><SiteHeader/><main>
<section className="page-hero dark-page-hero"><div className="container"><div className="eyebrow">SUZUKI DRIVE FOR BUSINESS</div><h1>Electric mobility<br/>at your scale.</h1><p className="muted">A dedicated corporate leasing proposition for organisations looking to make EV adoption simpler and more flexible.</p></div></section>
<section className="section"><div className="container"><div className="section-title"><div className="eyebrow">WHY SUZUKI DRIVE</div><h2>Built for real-world workplaces.</h2></div><div className="grid four-grid">{[['Employee mobility','Offer employees a flexible route into electric mobility.'],['Corporate leasing','Use company-owned or financed EV assets through a structured leasing model.'],['Workplace charging','Support EV adoption with workplace charging opportunities.'],['Flexible adoption','Start with shorter commitments and learn from real-world usage.']].map(([h,p])=><div className="card step-card" key={h}><h3>{h}</h3><p className="muted">{p}</p></div>)}</div></div></section>
<section className="section soft-page"><div className="container"><div className="section-title"><div className="eyebrow">FOCUS SEGMENTS</div><h2>Where corporate EV adoption can start.</h2></div><div className="grid persona-grid">{['IT / GCC campuses','Banks & NBFCs','Hospitals','PSUs','Industrial parks','Supplier ecosystem'].map(x=><div className="card persona" key={x}><h3>{x}</h3><p className="muted">A potential corporate use case for Suzuki Drive.</p></div>)}</div></div></section>
<section className="section"><div className="container form-card card"><div className="eyebrow">CORPORATE ENQUIRY</div><h2>Start a conversation.</h2><p className="muted">Tell us about your organisation and mobility requirement. The enquiry form can be connected to the final corporate lead workflow.</p><div className="grid form-grid"><input placeholder="Company name"/><input placeholder="Work email"/><input placeholder="Phone number"/><input placeholder="Number of vehicles"/></div><button className="btn btn-primary">Submit enquiry →</button></div></section>
<section className="section"><div className="container split"><div><div className="eyebrow">INDIVIDUAL LEASING</div><h2>Looking for an EV for yourself?</h2></div><Link className="btn btn-primary" href="/leasing">Explore Individual Leasing →</Link></div></section>
</main></>}
